config/routes.rb
Rails.application.routes.draw do
  match '/api/v2/auth/*path', to: AuthorizeController.action(:authorize), via: :all
  match '/api/v2/auth/', to: AuthorizeController.action(:authorize), via: :all
  mount API::Base, at: '/api'
end

app/models/document.rb
# frozen_string_literal: true

# User document model
class Document < ApplicationRecord
  include Encryptable

  acts_as_eventable prefix: 'document', on: %i[create]

  mount_uploader :upload, Barong::App.config.uploader

  STATES = %w[verified pending replaced rejected].freeze

  attr_encrypted :doc_number

  belongs_to :user

  validates :doc_type, :upload, presence: true
  validates :doc_type, inclusion: { in: DocumentTypes.list }
  validates :doc_expire, presence: true, if: -> { Barong::App.config.required_docs_expire }
  validates :metadata, data_is_json: true

  validates :doc_number, length: { maximum: 128 },
                         format: {
                           with: /\A[A-Za-z0-9\-\s]+\z/,
                           message: 'only allows letters and digits'
                         }, if: proc { |a| a.doc_number.present? }

  validate :doc_expire_not_in_the_past, if: -> { Barong::App.config.required_docs_expire }
  after_commit :start_document_kyc_verification, on: :create
  before_save :save_doc_number_index

  attr_writer :update_labels

  def as_json_for_event_api
    {
      user: user.as_json_for_event_api,
      upload: CGI::escape(upload.url),
      doc_type: doc_type,
      doc_number: doc_number,
      doc_expire: doc_expire,
      metadata: metadata,
      created_at: format_iso8601_time(created_at),
      updated_at: format_iso8601_time(updated_at)
    }
  end

  def sub_masked_doc_number
    doc_number.sub(/(?<=\A.{2})(.*)(?=.{2}\z)/) { |match| '*' * match.length } if doc_number
  end

  def verification_url
    "/api/v2/barong/admin/documents/#{id}"
  end

  private

  def start_document_kyc_verification
    KycService.document_step(self)
  end

  def update_labels
    @update_labels.nil? ? true : @update_labels
  end

  def doc_expire_not_in_the_past
    return if doc_expire.blank?

    errors.add(:doc_expire, :invalid) if doc_expire < Date.current
  end

  def save_doc_number_index
    if doc_number.present?
      self.doc_number_index = SaltedCrc32.generate_hash(doc_number)
    end
  end
end

# == Schema Information
#
# Table name: documents
#
#  id                   :bigint           not null, primary key
#  user_id              :bigint           unsigned, not null
#  upload               :string(255)
#  doc_type             :string(255)
#  doc_expire           :date
#  doc_number_encrypted :string(255)
#  doc_number_index     :bigint
#  doc_issue            :date
#  doc_category         :string(255)
#  identificator        :string(255)
#  metadata             :text(65535)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
# Indexes
#
#  index_documents_on_doc_number_index  (doc_number_index)
#  index_documents_on_user_id           (user_id)
#

app/controllers/api/v1/admin/documents.rb
# frozen_string_literal: true

require 'doorkeeper/grape/helpers'

module API
  module V1
    module Admin
      class Documents < Grape::API
        desc 'Documents related routes'
        resource :documents do
          desc 'Return documents of specific Account'
          get '/profile_documents' do
            authorize! :read, Document
            Profile.find_by_id(params[:id]).documents.as_json(only: %i[upload doc_type doc_number doc_expire])
          end
        end
      end
    end
  end
end

app/controllers/api/v1/documents.rb
# frozen_string_literal: true

module API
  module V1
    class Documents < Grape::API
      helpers Doorkeeper::Grape::Helpers

      desc 'Documents related routes'
      resource :documents do
        desc 'Return current user documents list'
        get '/' do
          current_account.documents.as_json(only: %i[upload doc_type doc_number doc_expire])
        end

        desc 'Upload a new document for current user'
        params do
          requires :doc_expire, :doc_type, :doc_number, :upload
        end

        post '/' do
          doc = current_account.documents.new(declared(params))
          if doc.save
            status 201
          else
            error!(doc.errors.full_messages.to_sentence, 400)
          end
        # temporary rescues the connection errors in fog-gooogle
        # TODO: check workability after adding carrierwave-google-storage gem
        rescue Excon::Error => e
          error!('Connection error', 500)
          logger.fatal(e)
        end
      end
    end
  end
end

app/controllers/api/v1/entities/document.rb
# frozen_string_literal: true

module API::V1::Entities
  class Document < Grape::Entity
    expose :upload,                                       documentation: { desc: 'Document upload, expected extensions jpg, jpeg, png' }
    expose :doc_type, as: :type, override: true,          documentation: { desc: 'Document type (passport, identity card, driver license)' }
    expose :doc_number, as: :number, override: true,      documentation: { desc: 'Document unique number' }
    expose :doc_expire, as: :expire_date, override: true, documentation: { desc: 'Expiry date of the document' }
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  before_action :authenticate_account!
  before_action :check_account_level

  def new
    @document = current_account.documents.new
  end

  def create
    if current_account.documents.count >= ENV.fetch('DOCUMENTS_LIMIT', 10)
      redirect_to index_path, alert: 'Maximum number of documents was reached'
    end

    @document = current_account.documents.new(document_params)
    if @document.save
      redirect_to index_path, notice: 'Document was successfully uploaded.'
    else
      flash[:alert] = 'Some fields are empty or invalid'
      render :new
    end
  end

private

  def check_account_level
    redirect_to new_phone_path if current_account.level < 2
  end

  def document_params
    params.require(:document)
          .permit(:doc_type, :doc_number, :doc_expire, :upload)
  end
end

app/controllers/web/documents_controller.rb
module Web
  class DocumentsController < ModuleController
    before_action :set_document, only: [:show, :edit, :update, :destroy]

    # GET /documents
    def index
      @documents = Document.all
    end

    # GET /documents/1
    def show
    end

    # GET /documents/new
    def new
      @document = Document.new
    end

    # GET /documents/1/edit
    def edit
    end

    # POST /documents
    def create
      @document = Document.new(document_params)

      if @document.save
        redirect_to @document, notice: 'Document was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /documents/1
    def update
      if @document.update(document_params)
        redirect_to @document, notice: 'Document was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /documents/1
    def destroy
      @document.destroy
      redirect_to documents_url, notice: 'Document was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_document
        @document = Document.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def document_params
        params.require(:document).permit(:customer_id, :upload, :upload_id, :upload_filename, :upload_content_size, :upload_content_type, :remove_upload, :doc_type, :doc_number, :doc_expire)
      end
  end
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="field col-12 ">
      <label>Document upload</label>
      <%= form.file_field :upload, id: :document_upload, class: 'dropify', 'data-allowed-file-extensions': 'png jpg jpeg pdf', 'data-max-file-size': '10M', 'data-default-file': document.upload.present? ? image_url(document.upload.url) : false %>
      </br>
    </div>
  </div>
  <div class="row">
    <div class="field col-6">
      <%= form.label :doc_type, 'Document type' %>
      <%= form.select(:doc_type, Document::TYPES, {id: :document_doc_type}, {class: 'form-control underlined'}) %>
    </div>

    <div class="field form-group">
      <%= form.label :doc_expire, 'Document expiry' %>
      <div class="down-arrow">
        <%= form.text_field :doc_expire, id: :document_doc_expire, class: 'datepicker-toggle form-control underlined', 'data-date-format': 'yyyy-mm-dd', 'data-date-start-date': '+1d', placeholder: 'Expiry date' %>
      </div>
    </div>

    <div class="field form-group col-12">
      <%= form.label :doc_number, 'Document number' %>
      <%= form.text_field :doc_number, id: :document_doc_number, class: 'px-1 form-control form-control-lg underlined', placeholder: 'AB123456' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-block btn-success' %>
  </div>
<% end %>

app/views/documents/id_doc.html.erb
<div class="text-center pt-1">
  <h2 class="font-weight-bold pt-4 pb-4"><span class="text-muted">Verification > </span>Id document</h2>
</div>

<div class="d-flex justify-content-center box-shadow">
  <div class="steps d-flex justify-content-between pb-2 px-5 mb-2">
    <div class="col-4 step-col first">
      <div class="step text-muted completed"></div>
      <small>Email</small>
    </div>
    <div class="col-4 step-col">
      <div class="step text-muted completed"></div>
      <small>Phone</small>
    </div>
    <div class="col-4 step-col last">
      <div class="step text-muted current"></div>
      <small>Document</small>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center px-5 py-4">
  <%= render 'form', document: @document %>
</div><br/>

app/views/documents/index.html.erb
<div class="container"></div>
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table class="table table-bordered table-sm text-center">
  <thead>
  <tr>
    <th>Doc type</th>
    <th>Doc number</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @documents.each do |document| %>
    <tr>
      <td><%= document.doc_type %></td>
      <td><%= document.doc_number %></td>
      <td><%= document.doc_file_name.present? ? image_tag(document.doc_file_name.url, width: '100', alt: 'Doc photo') : ''%></td>
      <td><%= link_to 'Edit', edit_document_path(document) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>
</div>

app/views/documents/new.html.erb
<div class="text-center pt-1">
  <h2 class="font-weight-bold pt-4 pb-4"><span class="text-muted">Verification > </span>Add document</h2>
</div>

<div class="d-flex justify-content-center box-shadow">
  <div class="steps d-flex justify-content-between pb-2 px-5 mb-2">
    <div class="col-4 step-col first">
      <div class="step text-muted completed"></div>
      <small>Email</small>
    </div>
    <div class="col-4 step-col">
      <div class="step text-muted completed"></div>
      <small>Phone</small>
    </div>
    <div class="col-4 step-col last">
      <div class="step text-muted current"></div>
      <small>Document</small>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center px-5 py-4">
  <%= render 'form', document: @document %>
</div><br/>

app/views/documents/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Doc type:</strong>
    <%= @document.doc_type %>
  </p>

  <p>
    <strong>Doc number:</strong>
    <%= @document.doc_number %>
  </p>

  <p>
    <%= @document.doc_file_name.present? ? image_tag(@document.doc_file_name.url, alt: 'Doc photo') : ''%>
  </p>

  <p>
    <%= @document.doc_file_name_2.present? ? image_tag(@document.doc_file_name.url, alt: 'Doc photo') : ''%>
  </p>

  <%= link_to 'Edit', edit_document_path(@document) %>
  <%= link_to 'Back', documents_path %>
</div>